=== theoldonee/Coursework_HTML/Favour/book.dtd
<!DOCTYPE catalog [ 
    <!ELEMENT catalog (book+)> 
    <!ELEMENT book (ISBN, Title, Author+, Publisher, Category, Edition, Date, Price, Description)> 
    <!ELEMENT ISBN (#PCDATA)> 
    <!ELEMENT Title (#PCDATA)> 
    <!ELEMENT Author (lastName, firstName)> 
    <!ELEMENT Publisher (#PCDATA)> 
    <!ELEMENT Category (#PCDATA)> 
    <!ELEMENT Edition (#PCDATA)> 
    <!ELEMENT Date (#PCDATA)> 
    <!ELEMENT Price (#PCDATA)> 
    <!ELEMENT Description (#PCDATA)> 
    <!ELEMENT lastName (#PCDATA)> 
    <!ELEMENT firstName (#PCDATA)> 
]>

=== theoldonee/Coursework_HTML/books.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="book.xsl"?>
<!-- <!DOCTYPE catalog SYSTEM "book.dtd"> -->

<catalog>
	<book>
		<Title>1984</Title>
		<ISBN>9780141182551</ISBN>
		<Author> 
			<firstName>George</firstName> 
			<lastName>Orwell</lastName>
		</Author>
		<Publisher>Penguin Books</Publisher>
		<Category>Fiction</Category>
		<Edition>Revised Edition</Edition>
		<Date>2000</Date>
		<Price>10.99</Price>
		<Description>A dystopian novel depicting a totalitarian regime where individuality and truth are suppressed.</Description>
		<Genre>Dystopian</Genre>
		<image>book_imgs/image1.png</image>
	</book>
	<book lang="en">
		<Title>To Kill a Mockingbird</Title>
		<ISBN>9780061122415</ISBN>
		<Author>
			<firstName>Harper</firstName> 
			<lastName>Lee</lastName>
		</Author>
		<Publisher>Harper Perennial Modern Classics</Publisher>
		<Category>Fiction</Category>
		<Edition>Anniversary Edition</Edition>
		<Date>2006</Date>
		<Price>14.99</Price>
		<Description>Set in the 1930s, the novel explores themes of racial injustice and moral growth through the eyes of a young girl in Alabama.</Description>
		<Genre>Bildungsroman</Genre>
		<image>book_imgs/image2.png</image>
	</book>
	<book>
		<Title>The Catcher in the Rye</Title>
		<ISBN>9780679720201</ISBN>
		<Author>
			<firstName>Jerome</firstName>
			<middleName>David</middleName>
			<lastName>Salinger</lastName>
		</Author>
		<Publisher>Little, Brown and Company</Publisher>
		<Category>Fiction</Category>
		<Edition>Reprint</Edition>
		<Date>1991</Date>
		<Price>8.99</Price>
		<Description>A coming-of-age novel following Holden Caulfield's journey through adolescence, grappling with alienation and identity.</Description>
		<Genre>Coming-of-age</Genre>
		<image>book_imgs/image3.png</image>
	</book>
	<book>
		<Title>Pride and Prejudice</Title>
		<ISBN>9780061120084</ISBN>
		<Author>
			<firstName>Jane</firstName> 
			<lastName>Austen</lastName>
		</Author>
		<Publisher>Harper Perennial</Publisher>
		<Category>Fiction</Category>
		<Edition>Reissue</Edition>
		<Date>2007</Date>
		<Price>7.99</Price>
		<Description>Regarded as one of the greatest works of romantic fiction, the novel explores love, marriage, and social class in early 19th-century England.</Description>
		<Genre>Romance, Classic</Genre>
		<image>book_imgs/image4.png</image>
	</book>
	<book>
		<Title>The Great Gatsby</Title>
		<ISBN>9780451524935</ISBN>
		<Author>
			<firstName>Francis</firstName> 
			<middleName>Scott </middleName>
			<lastName>Fitzgerald</lastName>
		</Author>
		<Publisher>Scribner</Publisher>
		<Category>Fiction</Category>
		<Edition>Reissue</Edition>
		<Date>2004</Date>
		<Price>16.00</Price>
		<Description>Set in the Roaring Twenties, the novel delves into the American Dream, wealth, and the illusion of success.</Description>
		<Genre>Jazz Age, Tragedy</Genre>
		<image>book_imgs/image5.png</image>
	</book>
	<book>
		<Title>One Hundred Years of Solitude</Title>
		<ISBN>9780679732241</ISBN>
		<Author>
			<firstName>Gabriel</firstName> 
			<middleName>Garcia</middleName> 
			<lastName>Marquez</lastName>
		</Author>
		<Publisher>Harper Perennial Modern Classics</Publisher>
		<Category>Fiction</Category>
		<Edition>Reprint</Edition>
		<Date>1998</Date>
		<Price>16.99</Price>
		<Description>A landmark novel in magical realism, tracing the Buend√≠a family's saga in the fictional town of Macondo.</Description>
		<Genre>Magical Realism</Genre>
		<image>book_imgs/image6.png</image>
	</book>
	<book>
		<Title>The Fault in Our Stars</Title>
		<ISBN>9780062315007</ISBN>
		<Author>
			<firstName>John</firstName> 
			<lastName>Green</lastName>
		</Author>
		<Publisher>Dutton Books</Publisher>
		<Category>Young Adult Fiction</Category>
		<Edition>Reprint</Edition>
		<Date>2014</Date>
		<Price>12.99</Price>
		<Description>A poignant love story between two teenagers battling cancer, exploring themes of life, love, and mortality.</Description>
		<Genre>Young Adult, Romance</Genre>
		<image>book_imgs/image7.png</image>
	</book>
	<book>
		<Title>The Bell Jar</Title>
		<ISBN>9780316769174</ISBN>
		<Author>
			<firstName>Sylvia</firstName>
			<lastName>Plath</lastName>
		</Author>
		<Publisher>Harper Perennial Modern Classics</Publisher>
		<Category>Fiction</Category>
		<Edition>Reprint</Edition>
		<date>2005</date>
		<Price>16.99</Price>
		<Description>A semi-autobiographical novel chronicling a young woman's descent into mental illness and her struggle for identity.</Description>
		<Genre>Semi-autobiographical</Genre>
		<image>book_imgs/image8.png</image>
	</book>
	<book>
		<Title>The Da Vinci Code</Title>
		<ISBN>9780385333849</ISBN>
		<Author>
			<firstName>Dan</firstName>
			<lastName>Brown</lastName>
		</Author>
		<Publisher>Anchor Books</Publisher>
		<Category>Mystery, Thriller</Category>
		<Edition>Reprint</Edition>
		<Date>2004</Date>
		<Price>9.99</Price>
		<Description>A gripping thriller intertwining art, religion, and secret societies, following symbologist Robert Langdon's quest to unravel ancient mysteries.</Description>
		<Genre>Mystery, Thriller</Genre>
		<image>book_imgs/image9.png</image>
	</book>
	<book>
		<Title>The Kite Runner</Title>
		<ISBN>9781400079988</ISBN>
		<Author>
			<firstName>Khaled</firstName>
			<lastName>Hosseini</lastName>
		</Author>
		<Publisher>Riverhead Books</Publisher>
		<Category>Fiction</Category>
		<Edition>Reprint</Edition>
		<Date>2004</Date>
		<Price>17.00</Price>
		<Description>A powerful narrative exploring friendship, betrayal, and redemption against the backdrop of Afghanistan's tumultuous history.</Description>
		<Genre>Historical</Genre>
		<image>book_imgs/image10.png</image>
	</book>
	<book>
		<Title>The Lovely Bones</Title>
		<ISBN>9780312283708</ISBN>
		<Author>
			<firstName>Alice</firstName> 
			<lastName>Sebold</lastName>
		</Author>
		<Publisher>Back Bay Books</Publisher>
		<Category>Fiction</Category>
		<Edition>Reprint</Edition>
		<Date>2004</Date>
		<Price>16.99</Price>
		<Description>A haunting and emotionally resonant novel narrated by a young girl who watches over her family and killer from the afterlife.</Description>
		<Genre>Supernatural</Genre>
		<image>book_imgs/image11.png</image>
	</book>
	<book>
		<Title>Life of Pi</Title>
		<ISBN>9781400034772</ISBN>
		<Author>
			<firstName>Yann</firstName> 
			<lastName>Martel</lastName>
		</Author>
		<Publisher>Mariner Books</Publisher>
		<Category>Fiction</Category>
		<Edition>Reprint</Edition>
		<Date>2003</Date>
		<Price>15.95</Price>
		<Description>A tale of survival and spirituality, following a young Indian boy's journey across the Pacific Ocean on a lifeboat with a Bengal tiger.</Description>
		<Genre>Adventure</Genre>
		<image>book_imgs/image12.png</image>
	</book>
	<book>
		<Title>Middlesex</Title>
		<ISBN>9780375704024</ISBN>
		<Author>
			<firstName>Jeffrey</firstName> 
			<lastName>Eugenides</lastName>
		</Author>
		<Publisher>Picador</Publisher>
		<Category>Fiction</Category>
		<Edition>Reprint</Edition>
		<Date>2003</Date>
		<Price>18.00</Price>
		<Description>An epic family saga spanning generations, exploring gender identity, immigration, and the American Dream.</Description>
		<Genre>Family Saga</Genre>
		<image>book_imgs/image13.png</image>
	</book>
	<book>
		<Title>The Hunger Games</Title>
		<ISBN>9780061768274</ISBN>
		<Author>
			<firstName>Suzanne</firstName>
			<lastName>Collins</lastName>
		</Author>
		<Publisher>Scholastic Press</Publisher>
		<Category>Young Adult Fiction</Category>
		<Edition>Reprint</Edition>
		<Date>2010</Date>
		<Price>12.99</Price>
		<Description>The first book in a thrilling dystopian trilogy, following Katniss Everdeen's journey in a televised fight to the death.</Description>
		<Genre>Action, Romance</Genre>
		<image>book_imgs/image14.png</image>
	</book>
	<book>
		<Title>Gone Girl</Title>
		<ISBN>9780316129185</ISBN>
		<Author>
			<firstName>Gillian</firstName>
			<lastName>Flynn</lastName>
		</Author>
		<Publisher>Broadway Books</Publisher>
		<Category>Mystery, Thriller</Category>
		<Edition>Reprint</Edition>
		<Date>2014</Date>
		<Price>16.00</Price>
		<Description>A gripping psychological thriller revolving around the disappearance of a woman and the ensuing media frenzy, filled with twists and unreliable narrators.</Description>
		<Genre>Mystery, Thriller</Genre>
		<image>book_imgs/image15.png</image>
	</book>
</catalog>
